PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT ?dim ?label ?range WHERE {
  ?dim a qb:DimensionProperty .
  OPTIONAL { ?dim rdfs:range ?range }
}
